platform :ios, '11.0'
use_frameworks!

target 'HBuilder-Vod' do

#  保利威 iOS 点播SDK
  pod 'PolyvVodSDK', '~> 2.22.0'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
end